networks:
  devnet:
    driver: bridge


services:
  backend:
    env_file: .env

    build: 
      context: backend
      dockerfile: Dockerfile

    depends_on:
      - postgres

    networks:
      - devnet

  frontend:

    build:
      context: frontend
      dockerfile: Dockerfile

    networks:
      - devnet

  postgres:

    image: postgres:17.0

    env_file: .env

    environment:
      POSTGRES_USER: ${APP_PG__USER}
      POSTGRES_PASSWORD: ${APP_PG__PASSWORD}
      POSTGRES_DB: ${APP_PG__DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - "./backend/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./data/pg/:/var/lib/postgresql/data/"

    networks:
      - devnet
  
  nginx:
    image: nginx:1.25.4-alpine

    ports:
      - "80:80"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend
      - frontend
    
    networks:
      - devnet